// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Roles_And_TodoCompletionNotes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "role_id",
                schema: "public",
                table: "users",
                type: "uuid",
                nullable: false,
                // Existing rows (created before roles existed) default to the "Registered" role.
                defaultValue: new Guid("9f0a1b1e-3b0a-4a1e-8c1a-000000000001"));

            migrationBuilder.AddColumn<string>(
                name: "completion_notes",
                schema: "public",
                table: "todo_items",
                type: "text",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "roles",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_roles", x => x.id);
                });

            migrationBuilder.InsertData(
                schema: "public",
                table: "roles",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { new Guid("9f0a1b1e-3b0a-4a1e-8c1a-000000000001"), "Registered" },
                    { new Guid("9f0a1b1e-3b0a-4a1e-8c1a-000000000002"), "Administrator" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_users_role_id",
                schema: "public",
                table: "users",
                column: "role_id");

            migrationBuilder.AddForeignKey(
                name: "fk_users_roles_role_id",
                schema: "public",
                table: "users",
                column: "role_id",
                principalSchema: "public",
                principalTable: "roles",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_users_roles_role_id",
                schema: "public",
                table: "users");

            migrationBuilder.DropTable(
                name: "roles",
                schema: "public");

            migrationBuilder.DropIndex(
                name: "ix_users_role_id",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "role_id",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "completion_notes",
                schema: "public",
                table: "todo_items");
        }
    }
}
